/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Kelas.User;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.SQLException;
import javax.swing.UIManager;

/**
 *
 * @author MysticWave
 */
public class FrameUser extends javax.swing.JFrame {

    /**
     * Creates new form FrameUser
     */
    public FrameUser() {
        initComponents();
        lb_hide.setVisible(true);
        lb_eye.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPG3Ver1 = new jpg3ver.JPG3Ver();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        tf_Email = new javax.swing.JTextField();
        tf_Password = new javax.swing.JPasswordField();
        tf_Fullname = new javax.swing.JTextField();
        cb_Status = new javax.swing.JComboBox<>();
        lb_eye = new javax.swing.JLabel();
        lb_hide = new javax.swing.JLabel();
        bt_Tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPG3Ver1.setColorEnd(new java.awt.Color(153, 204, 255));
        jPG3Ver1.setColorMiddle(new java.awt.Color(0, 153, 255));
        jPG3Ver1.setColorStart(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Biodata User Toko Kita");

        javax.swing.GroupLayout jPG3Ver1Layout = new javax.swing.GroupLayout(jPG3Ver1);
        jPG3Ver1.setLayout(jPG3Ver1Layout);
        jPG3Ver1Layout.setHorizontalGroup(
            jPG3Ver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPG3Ver1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPG3Ver1Layout.setVerticalGroup(
            jPG3Ver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPG3Ver1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPG3Ver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Fullname");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 227, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, -1, -1));

        tf_Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 92, 309, -1));

        tf_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tf_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 136, 309, -1));

        tf_Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 180, 309, -1));

        tf_Fullname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(tf_Fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 224, 309, -1));

        cb_Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak AKtif" }));
        jPanel1.add(cb_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 268, 309, -1));

        lb_eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye.png"))); // NOI18N
        lb_eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_eyeMouseClicked(evt);
            }
        });
        jPanel1.add(lb_eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 180, -1, 26));

        lb_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hide.png"))); // NOI18N
        lb_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hideMouseClicked(evt);
            }
        });
        jPanel1.add(lb_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 180, -1, 26));

        bt_Tambah.setBackground(new java.awt.Color(0, 0, 255));
        bt_Tambah.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_Tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_Tambah.setText("Tambah");
        bt_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TambahActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lb_eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_eyeMouseClicked
        lb_eye.setVisible(false);
        lb_hide.setVisible(true);

        tf_Password.setEchoChar('•');
    }//GEN-LAST:event_lb_eyeMouseClicked

    private void bt_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TambahActionPerformed
        try {
            User user = new Kelas.User();
            user.setUser_name(tf_Username.getText());
            user.setUser_email(tf_Email.getText());
            user.setUser_password(tf_Password.getText());
            user.setUser_fullname(tf_Fullname.getText());
            if (cb_Status.getSelectedItem().equals("Aktif")) {
                user.setUser_status(1);
            } else {
                user.setUser_status(0);
            }
            user.TambahUser();
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_bt_TambahActionPerformed

    private void lb_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hideMouseClicked
        lb_eye.setVisible(true);
        lb_hide.setVisible(false);

        tf_Password.setEchoChar((char) 0);
    }//GEN-LAST:event_lb_hideMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("Button.arc", 20);
            UIManager.put("Component.focusWidth", 2);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Tambah;
    private javax.swing.JComboBox<String> cb_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private jpg3ver.JPG3Ver jPG3Ver1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_eye;
    private javax.swing.JLabel lb_hide;
    private javax.swing.JTextField tf_Email;
    private javax.swing.JTextField tf_Fullname;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JTextField tf_Username;
    // End of variables declaration//GEN-END:variables
}
